import Head from 'next/head'
import Footer from '../components/Footer'
import Hero from '../components/Hero'
import Navbar from '../components/Navbar'
import About from './about'
import Contact from './contact'
import Menu from './menu'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Filiberto's Pizza delivery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name='viewport' content='width=device-width, initial-scale=1.0' />
        <meta name='Description' content='Filiberto Pizza delivery, order your pizzaon filiberto delivery website' />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Hero />
      <About />
      <Menu />
      <Contact />
      <Footer />
    </div>
  )
}
